# Generated by Django 3.2.6 on 2021-08-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='likes_add',
            field=models.IntegerField(default=1, verbose_name=1),
            preserve_default=False,
        ),
    ]
