# Generated by Django 3.2.6 on 2021-08-09 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_likes_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='song',
            name='likes_add',
        ),
    ]
