# Generated by Django 3.2.6 on 2021-08-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_remove_song_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.IntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
