# Generated by Django 3.2.6 on 2021-08-09 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_alter_song_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='likes',
        ),
    ]
